<FloatLayout>:

    Button:
        id:connect_btn
        text: "Connect"
        pos_hint: {"x" : 0, "top" : 1}
        size_hint: .15, .1
        color: 1 , 1 , 1 , 1
        background_color: 0.0, 1.0, 0.0, 0.3
     

    Button:
        id:decoller_btn
        text: "Takeoff"
        pos_hint: {"x" : 0.15, "top" : 1}
        size_hint: .15, .1
        color: 1 , 1 , 1 , 1
        background_color: 0.0, 1.0, 0.0, 0.3
      



    Button:
        id:photo_btn
        text: "Take photo"
        pos_hint: {"x" : 0.30, "top" : 1}
        size_hint: .2, .1
        color: 1 , 1 , 1 , 1
        background_color: 0.0, 1.0, 0.0, 0.3

    
    Button:
        id:capture_btn
        text: "Video"
        pos_hint: {"x" : 0.50, "top" : 1}
        size_hint: .2, .1
        color: 1 , 1 , 1 , 1
        background_color: 0.0, 1.0, 0.0, 0.3
    
    Button:
        id:land_btn
        text: "Land"
        pos_hint: {"x" : 0.70, "top" : 1}
        size_hint: .15, .1
        color: 1 , 1 , 1 , 1
        background_color: 0.0, 1.0, 0.0, 0.3
      
    